name: Testing the action

on: 
  push:

  workflow_dispatch:

permissions:
  contents: read
  issues: write
    
jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    #if: github.ref == 'refs/heads/main' # don't run on PRs
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - run: npm ci
      - run: npm run all

  test-tag-a-user:
    needs: build
    runs-on: ubuntu-latest
    #if: github.ref == 'refs/heads/main' # don't run on PRs or branches
    steps: 
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v3.3.0 # this will checkout the compiled Typescript
      
      #- uses: hmarr/debug-action@v2

      - uses: ./ # load and run local action
        name: Tag a user
        with: 
          issue: 1
          team: rajbos
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}