name: Issue trigger

on: 
  workflow_dispatch:

  issues:
    types: [opened]
    
permissions:
  contents: read
  issues: write

jobs:
  test-tag-a-user:
    runs-on: ubuntu-latest
    #if: github.ref == 'refs/heads/main' # don't run on PRs or branches
    steps: 
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.3.0 # this will checkout the compiled Typescript
     
      #- uses: hmarr/debug-action@v2

      - env:
          TITLE: ${{ github.event.issue.title }}
        run: |
         echo "Event information: ${{ github.event.issue.number }}"
         echo "Title: $TITLE"

      - uses: ./ # load and run the action
        name: Tag a user
        with: 
          issue: ${{ github.event.issue.number }}
          team: rajbos
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
